import random

exit_msgs = [
    "😢 Farewell! We'll miss you!",
    "👋 Saying goodbye is never easy. Take care!",
    "🌟 Wishing you all the best on your journey!",
    "🚀 Thanks for being part of our community!",
    "🌈 Goodbye! May your path be filled with joy!",
    "🎉 Sad to see you go. Come back soon!",
    "💔 Farewell, dear friend! Until we meet again!",
    "⭐️ It's not goodbye, it's see you later!",
    "😭 We'll cherish the moments we shared!",
    "✨ Your presence was a gift. Goodbye!",
    "🌠 Farewell! Your adventure awaits!",
    "👋 We hope our paths cross again!",
    "🌌 Wishing you a future filled with happiness!",
    "🎊 Until next time, take care!",
    "👋 It's not the end; it's a new beginning!",
    "🌙 Farewell! May your dreams shine bright!",
    "🌟 Goodbye, and may success follow you!",
    "💫 Your journey may take you far, but not from our hearts!",
    "🚀 Godspeed on your next adventure!",
    "🎈 Best wishes on your future endeavors!",
    "🌈 Farewell! Your impact will be remembered!",
    "🌠 Safe travels on your exciting journey!",
    "😢 It's tough to say goodbye, but we wish you well!",
    "🌟 Thank you for being a part of our story!",
    "🎊 Farewell! May your path be filled with positivity!",
    "⭐️ Goodbye, and may your days be full of sunshine!",
    "💔 We'll miss your presence. Take care!",
    "✨ Farewell! Your spirit will be with us!",
    "👋 Saying goodbye is a bittersweet moment!",
    "🌌 Your departure leaves a void. Best wishes!",
    "🚀 Godspeed! May your journey be extraordinary!",
    "🎈 Farewell! Your legacy remains in our hearts!",
    "😭 Goodbye, dear friend! Until we meet again!",
    "🌟 Wishing you success in all your endeavors!",
    "💫 You'll be missed. May your future be bright!",
    "🎊 Farewell! Your impact is immeasurable!",
    "👋 Goodbye, and may your dreams come true!",
    "🚀 May your next chapter be filled with triumph!",
    "🌠 It's not a goodbye; it's a 'see you later'!",
    "⭐️ Best of luck on your exciting journey!",
    "💔 Farewell! Your memories linger in our hearts!",
    "🌟 Your presence brought joy. Farewell!",
    "🎈 Wishing you a fantastic journey ahead!",
    "👋 Farewell! Until our paths cross again!",
    "🚀 May your future be as bright as your past!",
    "😭 Goodbye, dear friend! You'll be missed!",
    "🌈 Farewell! May your dreams become reality!",
    "🌌 Your next adventure awaits. Best of luck!",
    "🎉 Wishing you happiness in your next chapter!",
    "⭐️ Goodbye, and may your days be filled with joy!",
    "💫 As you embark on new adventures, remember us!",
    "✨ Farewell! Your impact is everlasting!",
]


def get_exit_message():
    return random.choice(exit_msgs)
