# Define the list of exit messages
exit_msgs = [
    "😢 {username} has left the group. We'll miss you!",
    "👋 {username} said goodbye. Wishing them all the best!",
    "😢 Farewell, {username}! You've been a fantastic member!",
    "👋 {username} left the chat. Best of luck on your journey!",
    "😢 {username} has departed. Thanks for being part of our community!",
    "👋 Goodbye, {username}! Your presence will be remembered.",
    "😢 {username} left the group. Take care and stay awesome!",
    "👋 {username} said farewell. We hope to see you again soon!",
    "😢 Farewell, {username}! Your contributions were invaluable.",
    "👋 {username} has left the chat. Wishing them success in all endeavors!",
    "😢 {username} departed. We'll cherish the moments we had together!",
    "👋 {username} said their goodbyes. Best wishes for the future!",
    "😢 Farewell, {username}! Your presence will be missed.",
    "👋 {username} left the group. Take a bow for your time here!",
    "😢 {username} has left us. Thanks for the memories!",
    "👋 {username} said their farewells. All the best on your next adventure!",
    "😢 {username} left the chat. We appreciate your time with us!",
    "👋 Farewell, {username}! Your legacy in the group remains!",
    "😢 {username} has departed. May your journey be filled with joy!",
    "👋 {username} said goodbye. We hope to cross paths again!",
    "😢 Farewell, {username}! Your impact on the group won't be forgotten.",
    "👋 {username} left the chat. We wish them success in everything!",
    "😢 {username} has left the group. Thanks for the laughter and fun!",
    "👋 Goodbye, {username}! Your presence was truly appreciated.",
    "😢 Farewell, {username}! Your mark on the group is everlasting.",
    "👋 {username} said their final goodbyes. Best of luck!",
    "😢 {username} left the chat. May your journey be filled with triumphs!",
    "👋 {username} has departed. We'll remember the good times!",
    "😢 Farewell, {username}! Your positive vibes will be missed.",
    "👋 {username} said goodbye. Wishing them success in all endeavors!",
    "😢 {username} left the group. Take care and stay connected!",
    "👋 {username} said their farewells. We appreciate your time here!",
    "😢 Farewell, {username}! Your contributions were invaluable.",
    "👋 {username} has left us. Thanks for the memories!",
    "😢 {username} left the chat. We wish them success in everything!",
    "👋 Farewell, {username}! Your legacy in the group remains!",
    "😢 {username} has departed. May your journey be filled with joy!",
    "👋 {username} said goodbye. We hope to cross paths again!",
    "😢 Farewell, {username}! Your impact on the group won't be forgotten.",
    "👋 {username} left the chat. We wish them success in everything!",
    "😢 {username} has left the group. Thanks for the laughter and fun!",
    "👋 Goodbye, {username}! Your presence was truly appreciated.",
    "😢 Farewell, {username}! Your mark on the group is everlasting.",
    "👋 {username} said their final goodbyes. Best of luck!",
    "😢 {username} left the chat. May your journey be filled with triumphs!",
    "👋 {username} has departed. We'll remember the good times!",
    "😢 Farewell, {username}! Your positive vibes will be missed.",
    f"👋 {username} said goodbye. For any further assistance, you can reach out to [Sasta Coder](https://t.me/sasta_coder)!",
    f"😢 Farewell, {username}! If you ever decide to return, [Sasta Coder](https://t.me/sasta_coder) will be here to welcome you!",
    f"👋 {username} left the chat. Wishing them all the best! For updates and more, follow [Sasta Coder](https://t.me/sasta_coder)!",
    f"😢 {username} has departed. For any inquiries or help, feel free to contact [Sasta Coder](https://t.me/sasta_coder)!",
]
