import random

welcome_msgs = [
    "👋 Welcome to our community! 🚀",
    "🎉 Glad to have you here! 🌟",
    "🌈 Get ready for some fun discussions! 🚀",
    "🚀 You're officially part of the crew! Welcome! 🌟",
    "👋 We're thrilled to have you here! 🚀",
    "🌟 Welcome to our chat! 🎉",
    "🚀 Join the conversation and enjoy! 🌈",
    "👋 Ready for some great moments? 🌟",
    "🌈 Excited to have you with us! 🚀",
    "🚀 Welcome to our friendly space! 🌟",
    "👋 The chat just got better with you here! Welcome! 🚀",
    "🌟 Your journey with us begins now! 🎉",
    "🎉 Get ready for an awesome time! 🚀",
    "🌈 Welcome to the squad! 🚀",
    "👋 We're delighted to welcome you! Let's chat! 🌟",
    "🚀 The party starts now! Welcome to the chat! 🎉",
    "🌟 Join the conversation and enjoy! 🚀",
    "🎉 Your presence makes this chat even better! 🌈",
    "👋 Welcome to our awesome community! 🚀",
    "🌈 You've just stepped into a fantastic chat! Welcome! 🌟",
    "🎉 Welcome! 🚀 Ready for some chat awesomeness?",
    "👋 We've been waiting for you! Welcome to the chat! 🌟",
    "🌟 Welcome to our space of endless conversations! 🚀",
    "🎉 You're not just a member; you're family now! Welcome! 🌈",
    "🌈 Get ready for an unforgettable chat experience! 🚀",
    "🚀 The chat just got upgraded with your arrival! Welcome! 🌟",
    "👋 Welcome! 🌈 Ready to dive into exciting conversations?",
    "🌟 Welcome to our community of chat enthusiasts! 🚀",
    "🎉 The chat is brighter now with you in it! Welcome! 🌈",
    "🌈 Welcome to our hub of interesting talks! 🚀",
    "👋 Welcome to the family! Get ready for amazing chats! 🌟",
    "🚀 Your presence adds a special spark to the chat! Welcome! 🎉",
    "🌟 Welcome! 🌈 Let's make this chat even more awesome together! 🚀",
    "🎉 The chat community just got better with you joining! Welcome! 🌟",
    "🌈 Welcome to the place where great conversations happen! 🚀",
    "👋 You're not just a member; you're a vital part of the chat! 🌟",
    "🚀 Welcome to the chat where every message is an adventure! 🎉",
    "🌟 Get ready for an incredible journey in our chat community! 🌈",
    "🎉 Welcome to our virtual space of endless discussions! 🚀",
    "🌈 You've officially joined the coolest chat on the block! Welcome! 🌟",
    "👋 The chat is buzzing with excitement because you're here! 🚀",
    "🚀 Welcome to the community that values every message! 🌈",
    "🌟 You're not just a newcomer; you're a chat VIP! Welcome! 🎉",
    "🎉 The chat is now complete with you as a part of it! Welcome! 🌈",
    "🌈 The chat experience just got an upgrade with you joining! 🚀",
    "👋 Welcome to the chat where every message is a gem! 🌟",
    "🚀 Your presence lights up the chat! Welcome aboard! 🎉",
    "🌟 Join the chat vibe and let's make it awesome! 🌈",
]


  
